[versions]
agp = "8.2.0-alpha14"
kotlin = "1.8.10"

[libraries]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

